<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot</name>
  <version>0.1.0</version>
  <description>Application nodes, configuration, and bringup for the Ackermann robot.</description>
  <maintainer email="lucasfoulkes@gmail.com">Lucas Foulkes</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>dualshock4_bringup</exec_depend>
  <exec_depend>dualshock4_teleop</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>mola_bridge_ros2</exec_depend>
  <exec_depend>mola_lidar_odometry</exec_depend>
  <exec_depend>pico_ackermann_driver</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <exec_depend>nav2_common</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ackermann_adaptive_controller</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
